### ISSUE TITLE
【エラー】`method_missing': undefined method `devise' for User:Class (NoMethodError)

### ISSUE THREAD

**Issue by yhirayama202207** [yhirayama202207/Furusato_Ambassador#1]
rails g devise Userを問題なく実行した後に、rails g devise Adminを実行しようとしたところ、下記のエラーが表示されました。

【エラー内容】
/home/ec2-user/.rvm/gems/ruby-3.1.2/gems/activerecord-6.1.7/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `devise' for User:Class (NoMethodError)

**Comment by yhirayama202207** [comment]
> rails g devise Userを問題なく実行した後に、rails g devise Adminを実行しようとしたところ、下記のエラーが表示されました。
> 
> 【エラー内容】 /home/ec2-user/.rvm/gems/ruby-3.1.2/gems/activerecord-6.1.7/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `devise' for User:Class (NoMethodError)

↓

【解決策】
routes.rbのdevise_for :usersの部分をコメントアウトしたところ、エラーが解決しrails g devise Adminを実行できました。
