### ISSUE TITLE
【エラー】`method_missing': undefined method `devise' for Admin:Class (NoMethodError)

### ISSUE THREAD

**Issue by yhirayama202207** [yhirayama202207/Furusato_Ambassador#2]
rails g devise:controllers publicを実行しようとしたところ、下記のエラーが表示されました。

【エラー内容】
/home/ec2-user/.rvm/gems/ruby-3.1.2/gems/activerecord-6.1.7/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `devise' for Admin:Class (NoMethodError)

**Comment by yhirayama202207** [comment]
> rails g devise:controllers publicを実行しようとしたところ、下記のエラーが表示されました。
> 
> 【エラー内容】 /home/ec2-user/.rvm/gems/ruby-3.1.2/gems/activerecord-6.1.7/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `devise' for Admin:Class (NoMethodError)

↓

【解決策】
①routes.rb から devise_for :adminとdevise_for :users の記述を削除
②rails d model Userとrails d model Adminを実行し、UserモデルとAdminモデルを削除
③rails g devise:install

上記の後に再度下記コマンドを実行したところ、問題なくモデルとコントローラーの作成ができました。
・rails g devise Admin
・rails g devise User
・rails g devise:controllers admin
・rails g devise:controllers public
