### ISSUE TITLE
【エラー】NoMethodError in Public::CommentsController#create

### ISSUE THREAD

**Issue by yhirayama202207** [yhirayama202207/Furusato_Ambassador#40]
【エラー】NoMethodError in Public::CommentsController#create
undefined method `id' for nil:NilClass

**Comment by yhirayama202207** [comment]
下記の修正をしてみましたが、上手くいきませんでした。

【修正前】
def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @article = @comment.article
    @comment.article_id = @article.id
    if @comment.save
      flash[:notice] = "新規コメント投稿が完了しました。"
      redirect_to article_path(@article.id)
    else
      redirect_to article_path(@article.id)
    end
  end

【修正後】
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @article = @comment.article
    if @comment.save
      flash[:notice] = "新規コメント投稿が完了しました。"
      redirect_to article_path(@article.id)
    else
      redirect_to article_path(@article.id)
    end
  end

**Comment by yhirayama202207** [comment]
もう一度コメントを投稿してみて、Terminal上で状況を確認

【Terminal上に表示された文】
Started POST "/comments" for 210.231.88.80 at 2022-11-14 07:22:59 +0000
Cannot render console from 210.231.88.80! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by Public::CommentsController#create as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "comment"=>{"comment"=>"美味しそうですね！"}, "commit"=>"新規登録"}
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/public/comments_controller.rb:13:in `create'
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/public/comments_controller.rb:15:in `create'
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/public/comments_controller.rb:15:in `create'
  TRANSACTION (0.1ms)  rollback transaction
  ↳ app/controllers/public/comments_controller.rb:15:in `create'
Completed 500 Internal Server Error in 14ms (ActiveRecord: 0.3ms | Allocations: 6987)


  
NoMethodError (undefined method `id' for nil:NilClass

      redirect_to article_path(@article.id)
                                       ^^^):
  
app/controllers/public/comments_controller.rb:19:in `create'

**Comment by yhirayama202207** [comment]
質問をさせていただき、下記の方法で解決することができました。

【Routing】
    resources :articles, only: [:new, :create, :show, :edit, :update, :index, :destroy] do
      resources :comments, only: [:create, :edit, :update, :index, :destroy]
    end

【Controller】
（articles/showアクション）
  def show
    @article = Article.find(params[:id])
    @user = @article.user
    @comment = @article.comments.build
    @comments = @article.comments.all
  end

（comments/createアクション）
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.article_id = params[:article_id]
    if @comment.save
      flash[:notice] = "新規コメント投稿が完了しました。"
      redirect_to article_path(@comment.article.id)
    else
      redirect_to article_path(@comment.article.id)
    end
  end

【View】
<h5>この記事にコメントする</h5>
<%= form_with model: @comment, url: article_comments_path(@comment.article_id), method: :post do |f| %>
    <%= f.text_field :comment, placeholder: "コメント" %>&emsp;
    <label>画像</label>
    <%= f.file_field :image, accept: "image/*" %></br>
    <%= f.submit "新規登録", class: "btn btn-success" %></br>
<% end %>
</br>
</br>
